---
# tasks file for logstash
- name: Logstash install
  ansible.builtin.apt:
    name: logstash
    state: present
    update_cache: true

- name: Enable logstash
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: true


- name: Copy logstash pipeline config
  ansible.builtin.template:
    src: "wordpress_debug.conf.j2"
    dest: "{{ logstash_pipeline_folder }}wordpress.conf"
    owner: root
    group: logstash
    mode: "0660"
  notify: Restart_logstash

- name: Wait for Logstash startup
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 300


- name: Create index-pattern
  ansible.builtin.uri:
    url: "{{ kibana_server_ip }}{{ kibana_api_url }}"
    method: POST
    body: "{{ '{\"attributes\": {\"title\": \"'+ kibana_index_pattern  +'\", \"timeFieldName\": \"'+  kibana_time_filter  +'\"}}' }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: true

- name: Copy debug.log example
  ansible.builtin.copy:
    src: "debug.log"
    dest: "{{ document_root }}{{ vhost_name }}/wp-content/debug.log"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"