---
- name: Test role
  hosts: VBOX
  become: true
  vars_prompt:
    - name: php_version
      prompt: "***** Choose php version. For example: 7.4 . | By default used php7.4 *****"
      default: "7.4"
      private: false

    - name: vhost_name
      prompt: "***** Set vhost name *****"
      default: "isdd.pp.ua"
      confirm: true
      private: false

    - name: db_action
      prompt: "***** If you want to create new db set - 1 | if you want to restore database set - 2 *****"
      private: false
      
    - name: db_dump_path
      prompt: "***** Set path to db dump | You can skip if create new db ******"
      default: "/home/mastdon/Documents/moving/onstyle.sql"
      private: false

    - name: db_name
      prompt: "***** Set database name *****"
      default: "raki_db"
      private: false

    - name: db_user
      prompt: "***** Set db user name *****"
      default: "foji"
      private: false

    - name: db_user_password
      prompt: "***** Set db user password *****"
      confirm: true

    - name: git_repo_url
      prompt: "***** Set git repositoty url | By default set official WordPress repositoty *****"
      default: "https://github.com/WordPress/WordPress.git"
      private: false



  roles:
    - swap
    - install_php
    - nginx_vhost_install
    # - letsencrypt
    - mysql_install
    - wordpress_install
    # - elasticsearch
    # - kibana
    # - logstash