---
# tasks file for mysql_install
- name: Install MySQL
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pip
    state: present
    update_cache: true

- name: Install MySQL module requirements
  ansible.builtin.pip:
    name:
      - PyMySQL
      - pip
    state: present

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: {{ mysql_socket }}

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '{{ db_name }}.*:ALL'
    state: present
    login_unix_socket: {{ mysql_socket }}