---
# tasks file for kibana
- name: Kibana install
  ansible.builtin.apt:
    name: kibana
    state: present
    update_cache: true

- name: Enable_kibana
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: true

- name: Copy Kibana config
  ansible.builtin.template:
    src: "kibana.yml.j2"
    dest: "{{ kibana_root_path }}kibana.yml"
    owner: root
    group: kibana
    mode: "0664"
  notify: 
    - Restart_Kibana
    - Nginx_restart

- name: Flush handlers
  meta: flush_handlers