---
# tasks file for wordpress_install
- name: Install Wordpress
  ansible.builtin.unarchive:
    src: "{{ src_url }}"
    dest: "{{ document_root }}{{ vhost_name }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copy wp-config.php to site directory
  ansible.builtin.template:
    src: "wp-config.php.j2"
    dest: "{{ document_root }}{{ vhost_name }}/wp-config.php"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  notify: Restart_NGINX 