---
# tasks file for elasticsearch
- name: Install https-transport
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - openssl
      - default-jdk
    state: present
    update_cache: true

- name: Import the Elastic Key
  ansible.builtin.apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Adding Elastic APT repository
  ansible.builtin.apt_repository:
    repo: "{{ es_apt_repository }}"
    state: present
    filename: "{{ es_apt_repositroy_file }}"
    update_cache: true

- name: Install elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    state: present
    update-cache: true

- name: Enable start elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: true

- name: Copy elasticsearch config
  ansible.builtin.template:
    src: "elasticsearch.yml.j2"
    dest: "{{ es_root_path }}elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: "0660"

- name: Copy jvm.options file for elasticsearch
  ansible.builtin.template:
    src: "jvm.options.j2"
    dest: "{{ es_root_path }}jvm.options"
    owner: root
    group: elasticsearch
    mode: "0660"
  notify: Restart_elasticsearch